app_name: company-profile-api
group: api
weight: 990
routes:
   1: ^/company-profile-api/healthcheck
   2: ^/company/(.*)/links.*
   3: ^/company/(.*)/company-detail
   4: ^/company/(.*)/uk-establishments
   5: ^/company/(.){8}$