server:
  port: 8081

logger:
  namespace: company-profile-api

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/company_profile}
      collection: ${MONGODB_COLLECTION:company_profile}

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

mongodb:
  transactional: ${TRANSACTIONS_ENABLED:true}
  company-profile:
    collection:
      name: ${COMPANY_PROFILE_COLLECTION_NAME:company_profile}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /company-profile-api
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true

feature:
  overseas-company-filing-allowed: ${FEATURE_FLAG_OVERSEAS_COMPANY_FILING_ALLOWED_08092025:false}