logger:
  namespace: company-profile-api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/company_profile}
      collection: ${MONGODB_COLLECTION:company_profile}

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

server:
  port: 8081

mongodb:
  company-profile:
    transactions: ${TRANSACTIONS_ENABLED:false}
    collection:
      name: ${COMPANY_PROFILE_COLLECTION_NAME:company_profile}
