logger:
  namespace: company-profile-api

mongo:
  company-profile-collection: company_profile

chs:
  kafka:
    api:
      endpoint: ${CHS_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false