logger:
  namespace: company-profile-api

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://127.0.0.1:27017/company_profile}
      collection: company_profile

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_API_KEY:chsApiKey}

springfox:
  documentation:
    auto-startup: false